bligress/urls.py
from django.conf.urls import patterns, include, url

from django.contrib import admin
admin.autodiscover()
from bligress import views

urlpatterns = patterns('',
     url(r'^$', views.index, name='index'),
     url(r'^accounts/login/$', 'django.contrib.auth.views.login', {'template_name': 'login.html'}),
     url(r'^login/$', views.loginview, name='login'),
     url(r'^logout/$', views.logoutview, name='logout'),
     url(r'^kanban/', include('kanban.urls', namespace="kanban")),
     url(r'^admin/', include(admin.site.urls)),
)

kanban/urls.py
from django.conf.urls import patterns, url

from kanban import views

urlpatterns = patterns('',
    url(r'^$', views.index, name='index'),
    url(r'^task/(?P<board_id>\d+)/(?P<task_id>\d+)/$', views.taskshow, name='taskshow'),
    url(r'^taskedit/(?P<board_id>\d+)/(?P<task_id>\d+)/$', views.taskedit, name='taskedit'),
    url(r'^taskclose/(?P<board_id>\d+)/(?P<task_id>\d+)/$', views.taskclose, name='taskclose'),
    url(r'^taskback/(?P<board_id>\d+)/(?P<task_id>\d+)/$', views.taskback, name='taskback'),
    url(r'^tasknew/(?P<board_id>\d+)/$', views.tasknew, name='tasknew'),
    url(r'^taskforw/(?P<board_id>\d+)/(?P<task_id>\d+)/$', views.taskforw, name='taskforw'),
    url(r'^taskcreate/(?P<board_id>\d+)/$', views.taskcreate, name='taskcreate'),
    url(r'^board/(?P<board_id>\d+)/$', views.boardshow, name='boardshow'),
    url(r'^boardnew/$', views.boardnew, name='boardnew'),
    url(r'^boardcreate/$', views.boardcreate, name='boardcreate'),
)

kanban/models.py
from django.db import models
from django.contrib.auth.models import User

class Task(models.Model):
    title = models.CharField(max_length=1024)
    start_date = models.DateTimeField('start date')
    done_date = models.DateTimeField('done date', null=True, blank=True)
    description = models.TextField(default="")
    hours = models.DecimalField(max_digits=5, decimal_places=2, default=0)
    owner = models.ForeignKey(User)
    group = models.ManyToManyField(User, related_name='u+', null=True, blank=True)
    phase = models.ForeignKey('Phase', null=False, default=0)
    PRIORITIES = (
        ("LO", "Low"),
        ("NO", "Normal"),
        ("HI", "High"),
        ("AS", "ASAP"),
    )
    priority = models.CharField(max_length=2, choices=PRIORITIES, default="NO")
    queue_number = models.IntegerField(default=0)

    def __unicode__(self):
        return self.title

    def get_priority(self):
        for p in self.PRIORITIES:
            if p[0] == self.priority:
                return p[1]
        return self.priority

class Phase(models.Model):
    name = models.CharField(max_length=256)
    size = models.IntegerField()
    order = models.IntegerField()

    def __unicode__(self):
        return self.name

class Board(models.Model):
    name = models.CharField(max_length=256)
    start_date = models.DateTimeField('start date')
    task = models.ManyToManyField('Task', related_name='task+', null=True, blank=True)
    phases = models.ManyToManyField('Phase', related_name='phase+', null=True, blank=True)

    def __unicode__(self):
        return self.name

class PhaseStatistics(models.Model):
    board = models.ForeignKey('Board')
    phase = models.ForeignKey('Phase')
    num_items = models.IntegerField()
    entry_avg = models.FloatField()
    leave_avg = models.FloatField()

class Statistics(models.Model):
    round_time = models.FloatField()
    board = models.ForeignKey('Board')
    phase = models.ForeignKey('PhaseStatistics')

kanban/views.py
from django.http import HttpResponse
from django.http import Http404

from django.shortcuts import render
from django.shortcuts import redirect

from django.template import RequestContext

from kanban.models import Task
from kanban.models import Board
from django.forms import ModelForm

from django.contrib.auth.models import User

from django.contrib.auth.decorators import login_required

@login_required
def index(request):
    boards = Board.objects.all()
    return render(request, 'index.html', {'boards': boards})

@login_required
def taskshow(request, board_id, task_id):
    try:
        task = Task.objects.get(pk=task_id)
    except:
        raise Http404

    return render(request, 'task.html', {'board_id': board_id, 'task': task})

@login_required
def taskclose(request, board_id, task_id):
    try:
        task = Task.objects.get(pk=task_id)
    except:
        raise Http404

    task.queue_number = -1
    task.save()

    return redirect('kanban:boardshow', board_id)

@login_required
def taskedit(request, board_id, task_id):
    try:
        task = Task.objects.get(pk=task_id)
    except:
        raise Http404

    if request.method == 'POST':
        try:
            board = Board.objects.get(pk=board_id)
        except:
            raise Http404
        form = TaskNewForm(data=request.POST, instance=task)
        if not form.is_valid():
            return render(request, 'taskedit.html', {'board_id': board_id, 'task': task, 'form': form})
        form.save()

        return redirect('kanban:taskshow', board_id, task_id)

    cf = TaskNewForm(instance=task)
    return render(request, 'taskedit.html', {'board_id': board_id, 'task': task, 'form': cf})


class TaskNewForm(ModelForm):
    class Meta:
        model = Task
        exclude = ["done_date", "queue_number", "owner", "group"]

    def __init__(self, *args, **kwargs):
        super(TaskNewForm, self).__init__(*args, **kwargs)
        self.fields['start_date'].widget.format = '%m/%d/%Y'
        self.fields['start_date'].widget.attrs.update({'class':'datePicker', 'readonly':'true'})

@login_required
def tasknew(request, board_id):
    try:
        board = Board.objects.get(pk=board_id)
    except:
        raise Http404
    cf = TaskNewForm()
    return render(request, 'tasknew.html', {'board_id': board_id, 'form': cf})

@login_required
def taskcreate(request, board_id):
    if request.method != 'POST':
        raise Http404

    form = TaskNewForm(data = request.POST)
    if not form.is_valid():
        return render(request, 'tasknew.html', {'board_id': board_id, 'form': form})

    try:
        board = Board.objects.get(pk=board_id)
    except:
        raise Http404

    try:
        user = User.objects.get(pk=1)
    except:
        raise Http404

    obj = form.save(commit = False)
    obj.owner = user
    obj.queue_number = 0
    obj.save()
    task_id = obj.id
    board.save()
    board.task.add(obj)

    return redirect('kanban:boardshow', board_id)

@login_required
def taskforw(request, board_id, task_id):
    try:
        board = Board.objects.get(pk=board_id)
    except:
        raise Http404
    try:
        task = Task.objects.get(pk=task_id)
    except:
        raise Http404

    nextphase = None
    getnext = False
    for phase in board.phases.order_by('order'):
        if getnext:
            nextphase = phase
            break 
        if phase == task.phase:
            getnext = True

    if nextphase is not None:
        task.phase = nextphase
        task.save()

    return redirect('kanban:boardshow', board_id)

@login_required
def taskback(request, board_id, task_id):
    try:
        board = Board.objects.get(pk=board_id)
    except:
        raise Http404
    try:
        task = Task.objects.get(pk=task_id)
    except:
        raise Http404

    prevphase = None
    getprev = False
    for phase in board.phases.order_by('order'):
        if phase == task.phase:
            getprev = True
            break
        prevphase = phase

    if getprev and prevphase is not None:
        task.phase = prevphase
        task.save()

    return redirect('kanban:boardshow', board_id)

@login_required
def boardshow(request, board_id):
    try:
        board = Board.objects.get(pk=board_id)
    except:
        raise Http404

    return render(request, 'board.html', {'board': board})

class BoardNewForm(ModelForm):
    class Meta:
        model = Board
        exclude = ["task"]

    def __init__(self, *args, **kwargs):
        super(BoardNewForm, self).__init__(*args, **kwargs)
        self.fields['start_date'].widget.format = '%m/%d/%Y'
        self.fields['start_date'].widget.attrs.update({'class':'datePicker', 'readonly':'true'})

@login_required
def boardnew(request):
    cf = BoardNewForm()
    return render(request, 'boardnew.html', {'form': cf})

@login_required
def boardcreate(request):
    if request.method != 'POST':
        raise Http404

    form = BoardNewForm(data=request.POST)
    if not form.is_valid():
        return render(request, 'boardnew.html', {'form': form})

    obj = form.save(commit = False)
    obj.save()
    form.save_m2m()
    if obj.phases.count() == 0:
        form = BoardNewForm(instance=obj, data=request.POST)
        return render(request, 'boardnew.html', {'form': form, 'errormsg': 'Please select at least one phase'} )
    board_id = obj.id

    return redirect('kanban:boardshow', board_id)

kanban/templates/board.html
{% load staticfiles %}

<link rel="stylesheet" type="text/css" href="{% static 'kanban.css' %}" />
<link rel="stylesheet" type="text/css" href="{% static 'board.css' %}" />

<div class="boardcontrols">
	<a class="boardcontrol" href={% url 'index' %}>List boards</a>
	<a class="boardcontrol" href={% url 'kanban:boardnew' %}>New board</a>
	<a class="boardcontrol" href={% url 'kanban:tasknew' board.id %}>New task</a>
	<a class="boardcontrol" href={% url 'logout' %}>Logout</a>
</div>

<div class="board">
    <h2 class="boardname"><a href="{% url 'kanban:boardshow' board.id %}">BOARD-{{ board.id }}</a>: {{ board.name }}</h2>

    <div class="boardstarted">Started: {{ board.start_date }}</div>

    {% for column in board.phases.all %}
    <div class="boardcolumn">
        <h3 class="boardphase">{{ column.name }}</h3>
        <div class="boardtasks">
        {% for task in board.task.all %}
            {% if task.phase == column %}
            {% if task.queue_number >= 0 %}
                <div class="boardtask" onclick="javascript: document.location='{% url 'kanban:taskshow' board.id task.id %}'">
                <span class="boardtaskname">{{ task.title }}</span>
                <span class="boardtaskblock">
                <a class="boardtaskback" href={% url 'kanban:taskback' board.id task.id %}>&lt;&lt;</a>
                <a class="boardtaskforward" href={% url 'kanban:taskforw' board.id task.id %}>&gt;&gt;</a>
                </span>
                <div class="floatstop"></div>
                </div>
            {% endif %}
            {% endif %}
        {% endfor %}
        </div>
    </div>
    {% endfor %}
    <div class="floatstop">
    </div>
</div>

kanban/templates/boardnew.html
<html>
{% load staticfiles %}

<head>
	<link rel="stylesheet" type="text/css" href="{% static 'board.css' %}" />
	<link rel="stylesheet" href="{% static 'jquery/ui.css' %}" />
	<script src="{% static 'jquery/jquery.js' %}"></script>
	<script src="{% static 'jquery/jquery-ui.js' %}"></script>
	<script>
	$(function() {
		$( "#id_start_date" ).datepicker();
	});
	</script>
</head>

<body>
<form action={% url 'kanban:boardcreate' %} method="post">
	{% csrf_token %}
	<h2>New board</h2>
	{% if errormsg %} 
	<div class="error">{{ errormsg }}</div>
	{% endif %} 
	<table>
	{{ form }}
	</table>
<div>
	<input type="submit" value="Create board"></input>
</div>
</body>

</form>
</html>

kanban/templates/index.html
{% load staticfiles %}

<link rel="stylesheet" type="text/css" href="{% static 'kanban.css' %}" />
<link rel="stylesheet" type="text/css" href="{% static 'board.css' %}" />

<div class="boardcontrols">
	<a class="boardcontrol" href={% url 'kanban:boardnew' %}>New board</a>
	<a class="boardcontrol" href={% url 'logout' %}>Logout</a>
</div>

<div class="boards">
	{% for board in boards %}
        <div class="board_selection"><a href={% url 'kanban:boardshow' board.id %}>BOARD-{{ board.id }}: {{ board.name }}</a></div>
	{% endfor %}
</div>

kanban/templates/login.html
{% load staticfiles %}
<head>
	<link rel="stylesheet" type="text/css" href="{% static 'board.css' %}" />
</head>

{% block content %}

{% if form.errors %}
<div class="error">Your username and password didn't match. Please try again.</div>
{% endif %}

<form method="post" action="{% url 'django.contrib.auth.views.login' %}">
{% csrf_token %}
<table>
<tr>
    <td>{{ form.username.label_tag }}</td>
    <td>{{ form.username }}</td>
</tr>
<tr>
    <td>{{ form.password.label_tag }}</td>
    <td>{{ form.password }}</td>
</tr>
</table>

<input type="submit" value="login" />
<input type="hidden" name="next" value="{{ next }}" />
</form>

{% endblock %}

kanban/templates/newtask.html
{% load staticfiles %}

<head>
    <link rel="stylesheet" type="text/css" href="{% static 'kanban.css' %}" />
    <link rel="stylesheet" type="text/css" href="{% static 'task.css' %}" />
    <link rel="stylesheet" href="{% static 'jquery/ui.css' %}" />
    <script src="{% static 'jquery/jquery.js' %}"></script>
    <script src="{% static 'jquery/jquery-ui.js' %}"></script>
    <script>
    $(function() {
            $( "#id_start_date" ).datepicker();
    });
    </script>
</head>


<form action={% url 'kanban:taskcreate' board_id %} method="post">
	{% csrf_token %}
	<h2>New task</h2>
	<table>
	{{ form }}
	</table>
<div class="toolbox">
	<input type="submit" value="Create task"></input>
        | <a href="{% url 'kanban:boardshow' board_id %}">Board</a>
</div>

</form>

kanban/templates/task.html
{% load staticfiles %}
{% load taskboard %}

<head>
	<link rel="stylesheet" type="text/css" href="{% static 'kanban.css' %}" />
	<link rel="stylesheet" type="text/css" href="{% static 'task.css' %}" />
</head>

{% if task %}
    <div class="task">
    <h2 class="tasktitle"><a href="{% url 'kanban:taskshow' board_id task.id %}">TASK-{{ task.id }}</a>: {{ task.title }}
    </h2>

    <div class="phase">Phase: {{ task.phase }}</div>

    <div class="owner">Owner: {{ task.owner.get_full_name }}</div>

    <div class="taskdesc">Desc:
    <div class="taskdescdata">{{ task.description | itemsurl:board_id }}</div>
    </div>

    <div class="tasktime">Time: {{ task.hours }} h</div>

    <div class="taskstarted">Started: {{ task.start_date }}</div>

    <div class="tasksprio">Priority: {{ task.get_priority }}</div>

    </div>
    <div class="toolbox">
        <a href="{% url 'kanban:taskedit' board_id task.id %}">Edit</a>
        | <a onclick="if (confirm('Are you sure to close task #{{ task.id }}: {{ task.title }} ?')) { document.location = '{% url 'kanban:taskclose' board_id task.id %}'}">Close task</a>
        | <a href="{% url 'kanban:boardshow' board_id %}">Back to board</a>
    </div>

{% else %}
    Error.
{% endif %}

kanban/templates/taskedit.html
{% load staticfiles %}

<head>
	<link rel="stylesheet" type="text/css" href="{% static 'kanban.css' %}" />
	<link rel="stylesheet" type="text/css" href="{% static 'task.css' %}" />
	<link rel="stylesheet" href="{% static 'jquery/ui.css' %}" />
	<script src="{% static 'jquery/jquery.js' %}"></script>
	<script src="{% static 'jquery/jquery-ui.js' %}"></script>
	<script>
	$(function() {
		$( "#id_start_date" ).datepicker();
	});
	</script>
</head>


<form action={% url 'kanban:taskedit' board_id task.id %} method="post">
	{% csrf_token %}
	<h2>Edit task: <a href="{% url 'kanban:taskshow' board_id task.id %}">TASK-{{ task.id }}</a></h2>
	<table>
	{{ form }}
	</table>
<div class="toolbox">
	<input type="submit" value="Save"></input>
        | <a onclick="if (confirm('Are you sure to close task #{{ task.id }}: {{ task.title }} ?')) { document.location = '{% url 'kanban:taskclose' board_id task.id %}'}">Close task</a>
        | <a href="{% url 'kanban:taskshow' board_id task.id %}">Back</a>
</div>

</form>

kanban/templates/tasknew.html
{% load staticfiles %}

<head>
    <link rel="stylesheet" type="text/css" href="{% static 'kanban.css' %}" />
    <link rel="stylesheet" type="text/css" href="{% static 'task.css' %}" />
    <link rel="stylesheet" href="{% static 'jquery/ui.css' %}" />
    <script src="{% static 'jquery/jquery.js' %}"></script>
    <script src="{% static 'jquery/jquery-ui.js' %}"></script>
    <script>
    $(function() {
            $( "#id_start_date" ).datepicker();
    });
    </script>
</head>


<form action={% url 'kanban:taskcreate' board_id %} method="post">
	{% csrf_token %}
	<h2>New task</h2>
	<table>
	{{ form }}
	</table>
<div class="toolbox">
	<input type="submit" value="Create task"></input>
        | <a href="{% url 'kanban:boardshow' board_id %}">Back to board</a>
</div>

</form>